# --- [DevOS: Tmux Elite Config] ---

# 1. The Prefix (The C-Space way)
set -g prefix C-Space
unbind C-b
bind C-Space send-prefix

# 2. Quality of Life
set -g default-terminal "screen-256color"
set -g base-index 1
set -g pane-base-index 1
set-option -g renumber-windows on
set -g status-position top
set -g mouse on
set -g status-style bg=black,fg=white
# 3. THE PERMANENT SHELL FIX
# This forces Tmux to start a non-login interactive shell (Loads .zshrc automatically)
set -g default-command "/usr/bin/zsh"

# 4. Keybindings
bind r source-file ~/.tmux.conf \; display "Reloaded!"
bind v split-window -h -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}"

# 5. Plugins (TPM)
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'omerxx/tmux-sessionx'

# 6. SessionX & Catppuccin Elite Config
set -g @sessionx-bind 'o'
set -g @sessionx-zoxide-mode 'on'
set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_text "#W"
set -g @catppuccin_window_current_text "#W"

# Initialize TPM (Keep at the bottom)
run '~/.tmux/plugins/tpm/tpm'