$HOME/.config/hypr/themes/theme.conf|> $HOME/.config/hypr/themes/colors.conf

$GTK_THEME = Adwaita-dark
$ICON_THEME = Papirus-Dark
$COLOR_SCHEME = prefer-dark

exec = gsettings set org.gnome.desktop.interface icon-theme $ICON_THEME
exec = gsettings set org.gnome.desktop.interface gtk-theme $GTK_THEME
exec = gsettings set org.gnome.desktop.interface color-scheme $COLOR_SCHEME

general {
    gaps_in = 3
    gaps_out = 8
    border_size = 2
    col.active_border = rgba(d97757ff) rgba(a85c3aff) 45deg
    col.inactive_border = rgba(3d302bcc)
    layout = dwindle
    resize_on_border = true
}

group {
    col.border_active = rgba(d97757ff) rgba(a85c3aff) 45deg
    col.border_inactive = rgba(3d302bcc)
    col.border_locked_active = rgba(d97757ff)
    col.border_locked_inactive = rgba(3d302bcc)
}

decoration {
    rounding = 10
    shadow:enabled = true
    shadow:range = 6
    shadow:render_power = 2
    shadow:color = rgba(1a111088)

    blur {
        enabled = yes
        size = 6
        passes = 3
        new_optimizations = on
        ignore_opacity = on
        xray = false
    }
}

layerrule = blur,waybar
